/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import data.Connect;
import data.KhachHangData;
import data.SachData;
import data.ThamSoData;
import data.Update;
import static data.Update.ps;
import static data.Update.rs;
import data.connectionMysql;
import design.PhieuNhapSach;
import design.frmSinhVien;
import design.test;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;
import object.KhachHang;
import object.Sach;
import object.ThamSo;

/**
 *
 * @author HungLuu
 */
public class JMain extends javax.swing.JFrame {

    Connect con = new Connect();
    Connection conn = con.getConnect();
    String sqlts = "select * from thamso";
    String sqls = "select * from sach";
    String sqlKH = "select * from khachhang";
    String sqlBaoCaoCongNo = "select * from chitietbaocaocongno";
    String sqlBaoCaoTon = "select * from chitietbaocaoton";
    String sqlThamSo = "select * from thamso";
    Sach s = new Sach();
    KhachHang kh = new KhachHang();
    String str;
    ThamSo ts = new ThamSo();

    /**
     * Creates new form JMain
     */
    public JMain() {
        initComponents();
        hienThiDanhSachSach();
        hienThiDanhSachKhachHang();
        hienThiThamSo();
        txtMaKH.setText(Update.CodeXXX());
        // disconnect();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabSach = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        txtTimKiemSach = new javax.swing.JTextField();
        btnTimSach = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtMaSach = new javax.swing.JTextField();
        txtTenSach = new javax.swing.JTextField();
        txtTacGia = new javax.swing.JTextField();
        txtDonGia = new javax.swing.JTextField();
        txtSLNhap = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableSach = new javax.swing.JTable();
        btnThemSach = new javax.swing.JButton();
        btnCapNhatSach = new javax.swing.JButton();
        btnXóa = new javax.swing.JButton();
        txtTheLoai = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        txtTimKH = new javax.swing.JTextField();
        btnTimKH = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtMaKH = new javax.swing.JTextField();
        txtTenKH = new javax.swing.JTextField();
        txtDienThoai = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtDiaChiKH = new javax.swing.JTextField();
        txtSoTienNo = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbKhachHang = new javax.swing.JTable();
        btnThemKH = new javax.swing.JButton();
        btnCapNhapKH = new javax.swing.JButton();
        btnXoaKH = new javax.swing.JButton();
        btnNhapLaiKH = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btnBCTon = new javax.swing.JButton();
        btnBCCongNo = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbBaoCao = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtQDNhapMin = new javax.swing.JTextField();
        txtQDTonTrcKhiNhap = new javax.swing.JTextField();
        txtQDTienNoMax = new javax.swing.JTextField();
        txtQDTonMinSauKhiBan = new javax.swing.JTextField();
        btnQDMacDinh = new javax.swing.JButton();
        btnQDLuu = new javax.swing.JButton();
        txtApDungQD = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        txtTimKiemSach.setText("nhập mã sách mà bạn muốn tìm");

        btnTimSach.setText("Tìm sách");

        jLabel1.setText("Mã Sách");

        jLabel2.setText("Tên sách");

        jLabel3.setText("Thể loại");

        jLabel4.setText("Tác giả");

        jLabel5.setText("Đơn giá");

        jLabel6.setText("SL tồn");

        txtMaSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaSachActionPerformed(evt);
            }
        });

        TableSach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TableSach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableSachMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TableSachMousePressed(evt);
            }
        });
        TableSach.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TableSachKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(TableSach);

        btnThemSach.setText("Thêm sách mới");
        btnThemSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemSachActionPerformed(evt);
            }
        });

        btnCapNhatSach.setText("Cập nhật thông tin sách");
        btnCapNhatSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatSachActionPerformed(evt);
            }
        });

        btnXóa.setText("Xóa");
        btnXóa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXóaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtTimKiemSach, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnTimSach)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnThemSach, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(25, 25, 25)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtMaSach, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                                    .addComponent(txtTenSach)
                                    .addComponent(txtTacGia)
                                    .addComponent(txtDonGia)
                                    .addComponent(txtSLNhap)
                                    .addComponent(txtTheLoai)))
                            .addComponent(btnCapNhatSach, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                            .addComponent(btnXóa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTimKiemSach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTimSach)
                    .addComponent(btnThemSach))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtMaSach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtTenSach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtTheLoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtTacGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtDonGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtSLNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCapNhatSach)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnXóa)
                        .addGap(0, 105, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        tabSach.addTab("Quản lý Sách", jPanel1);

        txtTimKH.setText("nhập mã khác hàng mà bạn muốn tìm");

        btnTimKH.setText("Tìm khách hàng");

        jLabel7.setText("Mã Khách hàng");

        jLabel8.setText("Tên khách hàng");

        jLabel9.setText("Điện thoại");

        jLabel10.setText("Email");

        jLabel11.setText("Địa chỉ");

        jLabel12.setText("Số tiền nợ");

        txtMaKH.setEnabled(false);

        txtTenKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenKHActionPerformed(evt);
            }
        });

        txtDiaChiKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiaChiKHActionPerformed(evt);
            }
        });

        tbKhachHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbKhachHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbKhachHangMouseClicked(evt);
            }
        });
        tbKhachHang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tbKhachHangKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(tbKhachHang);

        btnThemKH.setText("Đăng kí khách hàng mới");
        btnThemKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemKHActionPerformed(evt);
            }
        });

        btnCapNhapKH.setText("Cập nhật thông tin khách hàng");
        btnCapNhapKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhapKHActionPerformed(evt);
            }
        });

        btnXoaKH.setText("Xóa khách hàng");
        btnXoaKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaKHActionPerformed(evt);
            }
        });

        btnNhapLaiKH.setText("Nhập lại");
        btnNhapLaiKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhapLaiKHActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtTimKH, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnTimKH)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12))
                                .addGap(26, 26, 26)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtMaKH)
                                    .addComponent(txtTenKH)
                                    .addComponent(txtDienThoai)
                                    .addComponent(txtEmail)
                                    .addComponent(txtDiaChiKH)
                                    .addComponent(txtSoTienNo, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)))
                            .addComponent(btnThemKH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCapNhapKH, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                            .addComponent(btnXoaKH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnNhapLaiKH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTimKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTimKH))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtMaKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtTenKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(txtDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txtDiaChiKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSoTienNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addGap(17, 17, 17)
                        .addComponent(btnNhapLaiKH)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnThemKH)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCapNhapKH)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnXoaKH)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE))
                .addContainerGap())
        );

        tabSach.addTab("Quản lý Khách Hàng", jPanel2);

        btnBCTon.setText("Báo cáo tồn");
        btnBCTon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBCTonActionPerformed(evt);
            }
        });

        btnBCCongNo.setText("Báo cáo công nợ");
        btnBCCongNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBCCongNoActionPerformed(evt);
            }
        });

        tbBaoCao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tbBaoCao);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnBCTon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBCCongNo, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 347, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnBCTon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBCCongNo)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        tabSach.addTab("Admin và Báo cáo nhà sách", jPanel3);

        jLabel13.setText("Số lượng nhập ít nhất");

        jLabel14.setText("Số lượng tồn trước khi nhập");

        jLabel15.setText("Số tiền nợ tối đa của khách hàng");

        jLabel16.setText("Số lượng sách tồn tối tiểu sau khi bán");

        jLabel17.setText("Áp dụng quy định với khách hàng có đơn giá không vượt quá số tiền nợ");

        txtQDNhapMin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQDNhapMinActionPerformed(evt);
            }
        });

        btnQDMacDinh.setText("Mặc định");
        btnQDMacDinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQDMacDinhActionPerformed(evt);
            }
        });

        btnQDLuu.setText("Lưu");
        btnQDLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQDLuuActionPerformed(evt);
            }
        });

        txtApDungQD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApDungQDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17))
                .addGap(21, 21, 21)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtQDTonTrcKhiNhap)
                    .addComponent(txtQDTienNoMax)
                    .addComponent(txtQDTonMinSauKhiBan, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                    .addComponent(txtApDungQD)
                    .addComponent(txtQDNhapMin))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnQDMacDinh)
                    .addComponent(btnQDLuu, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(197, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtQDNhapMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnQDMacDinh))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtQDTonTrcKhiNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnQDLuu)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(txtQDTienNoMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(txtQDTonMinSauKhiBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txtApDungQD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(225, Short.MAX_VALUE))
        );

        tabSach.addTab("Chỉnh sửa quy định trong quản lí nhà sách", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabSach)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabSach)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void hienThiBaoCaoCongNo() {
        try {
            ps = conn.prepareStatement(sqlBaoCaoCongNo);
            rs = ps.executeQuery();
        } catch (SQLException ex) {
            Logger.getLogger(PhieuNhapSach.class.getName()).log(Level.SEVERE, null, ex);
        }

        tbBaoCao.setModel(DbUtils.resultSetToTableModel(rs));
        tbBaoCao.getColumnModel().getColumn(0).setHeaderValue("Mã Chi tiết");
        tbBaoCao.getColumnModel().getColumn(1).setHeaderValue("Nợ đầu");
        tbBaoCao.getColumnModel().getColumn(2).setHeaderValue("Nợ cuối");
        tbBaoCao.getColumnModel().getColumn(3).setHeaderValue("Nợ phát sinh");
        tbBaoCao.getColumnModel().getColumn(4).setHeaderValue("Mã báo cáo công nợ");
        tbBaoCao.getColumnModel().getColumn(5).setHeaderValue("Mã khách hàng");
        // Forces the header to resize and repaint itself
        tbBaoCao.getTableHeader().resizeAndRepaint();
    }

    public void hienThiBaoCaoTon() {
        try {
            ps = conn.prepareStatement(sqlBaoCaoTon);
            rs = ps.executeQuery();
        } catch (SQLException ex) {
            Logger.getLogger(PhieuNhapSach.class.getName()).log(Level.SEVERE, null, ex);
        }

        tbBaoCao.setModel(DbUtils.resultSetToTableModel(rs));
        tbBaoCao.getColumnModel().getColumn(0).setHeaderValue("Mã chi tiết tồn");
        tbBaoCao.getColumnModel().getColumn(1).setHeaderValue("Tồn phát sinh");
        tbBaoCao.getColumnModel().getColumn(2).setHeaderValue("Tồn đầu");
        tbBaoCao.getColumnModel().getColumn(3).setHeaderValue("Tồn cuối");
        tbBaoCao.getColumnModel().getColumn(4).setHeaderValue("Mã báo cáo tồn");
        tbBaoCao.getColumnModel().getColumn(5).setHeaderValue("Mã sách");
        // Forces the header to resize and repaint itself
        tbBaoCao.getTableHeader().resizeAndRepaint();
    }

    public void hienThiDanhSachSach() {

        try {
            ps = conn.prepareStatement(sqls);
            rs = ps.executeQuery();
        } catch (SQLException ex) {
            Logger.getLogger(PhieuNhapSach.class.getName()).log(Level.SEVERE, null, ex);
        }

        TableSach.setModel(DbUtils.resultSetToTableModel(rs));
        TableSach.getColumnModel().getColumn(0).setHeaderValue("Mã sách");
        TableSach.getColumnModel().getColumn(1).setHeaderValue("Tên sách");
        TableSach.getColumnModel().getColumn(2).setHeaderValue("Thể Loại");
        TableSach.getColumnModel().getColumn(3).setHeaderValue("Tác Giả");
        TableSach.getColumnModel().getColumn(4).setHeaderValue("Đơn Giá");
        TableSach.getColumnModel().getColumn(5).setHeaderValue("Số Lượng Tồn");
        // Forces the header to resize and repaint itself
        TableSach.getTableHeader().resizeAndRepaint();

        //con.FreeConnection();
    }

    public void hienThiDanhSachKhachHang() {

        try {
            ps = conn.prepareStatement(sqlKH);
            rs = ps.executeQuery();
        } catch (SQLException ex) {
            Logger.getLogger(PhieuNhapSach.class.getName()).log(Level.SEVERE, null, ex);
        }

        tbKhachHang.setModel(DbUtils.resultSetToTableModel(rs));
        tbKhachHang.getColumnModel().getColumn(0).setHeaderValue("Mã khách hàng");
        tbKhachHang.getColumnModel().getColumn(1).setHeaderValue("Tên khách hàng");
        tbKhachHang.getColumnModel().getColumn(2).setHeaderValue("Điện thoại");
        tbKhachHang.getColumnModel().getColumn(3).setHeaderValue("Địa chỉ");
        tbKhachHang.getColumnModel().getColumn(4).setHeaderValue("Email");
        tbKhachHang.getColumnModel().getColumn(5).setHeaderValue("Số nợ");
        // Forces the header to resize and repaint itself
        tbKhachHang.getTableHeader().resizeAndRepaint();

        // con.FreeConnection();
    }

//     public void disconnect(){
//         con.FreeConnection();
//     }
    public void hienThiThamSo() {
        ResultSet rs = ThamSoData.showTextFile(sqlThamSo);

        try {
            if (rs.next()) {
                txtQDNhapMin.setText(rs.getString("Soluongnhapitnhat"));
                txtQDTonTrcKhiNhap.setText(rs.getString("soluongtontoidatruockhinhap"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(PhieuNhapSach.class.getName()).log(Level.SEVERE, null, ex);
        }
    }


    private void txtTenKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenKHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenKHActionPerformed

    private void txtDiaChiKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiaChiKHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiaChiKHActionPerformed

    private void btnThemSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemSachActionPerformed
        JNhapSach NS = new JNhapSach();
        NS.show();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnThemSachActionPerformed

    private void btnCapNhatSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatSachActionPerformed
        // TODO add your handling code here:
        if (txtMaSach.getText().isEmpty() | txtTenSach.getText().isEmpty() | txtTheLoai.getText().isEmpty() | txtTacGia.getText().isEmpty() | txtSLNhap.getText().isEmpty() | txtDonGia.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Hãy chọn 1 đầu sách và cập nhật lại thông tin của sách");
        } else {
            s.setMaSach(txtMaSach.getText().trim());
            s.setTenSach(txtTenSach.getText().trim());
            s.setTheLoai(txtTheLoai.getText().trim());
            int SLN = Integer.parseInt(txtSLNhap.getText());
            s.setSoLuongTon(SLN);
            s.setTacGia(txtTacGia.getText().trim());
            int DG = Integer.parseInt(txtDonGia.getText());
            s.setDonGia(DG);
            SachData.Update(s);
            hienThiDanhSachSach();
        }
    }//GEN-LAST:event_btnCapNhatSachActionPerformed

    private void txtMaSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaSachActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaSachActionPerformed

    private void TableSachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableSachMouseClicked
        // TODO add your handling code here:
        int i = TableSach.getSelectedRow();
        TableModel model = TableSach.getModel();
        txtMaSach.setText(model.getValueAt(i, 0).toString());
        txtTenSach.setText(model.getValueAt(i, 1).toString());
        txtTheLoai.setText(model.getValueAt(i, 2).toString());
        txtTacGia.setText(model.getValueAt(i, 3).toString());
        txtDonGia.setText(model.getValueAt(i, 4).toString());
        txtSLNhap.setText(model.getValueAt(i, 5).toString());
    }//GEN-LAST:event_TableSachMouseClicked

    private void TableSachMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableSachMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_TableSachMousePressed

    private void TableSachKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TableSachKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_TableSachKeyPressed

    private void tbKhachHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbKhachHangMouseClicked
        // TODO add your handling code here:
        int i = tbKhachHang.getSelectedRow();
        TableModel model = tbKhachHang.getModel();
        txtMaKH.setText(model.getValueAt(i, 0).toString());
        txtTenKH.setText(model.getValueAt(i, 1).toString());
        txtDienThoai.setText(model.getValueAt(i, 2).toString());
        txtDiaChiKH.setText(model.getValueAt(i, 3).toString());
        txtEmail.setText(model.getValueAt(i, 4).toString());
        txtSoTienNo.setText(model.getValueAt(i, 5).toString());
    }//GEN-LAST:event_tbKhachHangMouseClicked

    private void tbKhachHangKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbKhachHangKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbKhachHangKeyPressed

    private void btnBCTonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBCTonActionPerformed
        // TODO add your handling code here:
        hienThiBaoCaoTon();
    }//GEN-LAST:event_btnBCTonActionPerformed

    private void btnBCCongNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBCCongNoActionPerformed
        // TODO add your handling code here:
        hienThiBaoCaoCongNo();
    }//GEN-LAST:event_btnBCCongNoActionPerformed

    private void btnXóaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXóaActionPerformed
        // TODO add your handling code here:
        SachData.Delete(txtMaSach.getText().trim());
        hienThiDanhSachSach();
    }//GEN-LAST:event_btnXóaActionPerformed

    private void btnCapNhapKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhapKHActionPerformed
        // TODO add your handling code here:
        if (txtTenKH.getText().isEmpty() | txtDiaChiKH.getText().isEmpty() | txtDienThoai.getText().isEmpty() | txtEmail.getText().isEmpty() | txtSoTienNo.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Chọn 1 khách hàng trong danh sách để thay đổi thông tin");
        } else {
            kh.setMaKhachHang(txtMaKH.getText().trim());
            kh.setHoTenKhachHang(txtTenKH.getText().trim());
            kh.setDiaChi(txtDiaChiKH.getText().trim());
            kh.setEmaill(txtEmail.getText().trim());
            String txt = txtSoTienNo.getText();
            String sdt = txtDienThoai.getText().trim();
            try {
                int num = Integer.parseInt(txt);
                int sdtcheck = Integer.parseInt(sdt);
                kh.setSoDienThoai(sdt);
                kh.setSoTienNo(num);
                KhachHangData.Update(kh);
                hienThiDanhSachKhachHang();
                // is an integer!
            } catch (NumberFormatException e) {
                // not an integer!
                JOptionPane.showMessageDialog(this, "số tiền nợ hoặc số điện thoại của khách hàng không hợp lệ vui lòng nhập lại");
            }
        }
    }//GEN-LAST:event_btnCapNhapKHActionPerformed

    private void btnNhapLaiKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhapLaiKHActionPerformed
        // TODO add your handling code here:
//        txtMaKH.setText("");
        txtMaKH.setText(Update.CodeXXX());
        txtTenKH.setText("");
        txtDiaChiKH.setText("");
        txtDienThoai.setText("");
        txtEmail.setText("");
        txtSoTienNo.setText("");
    }//GEN-LAST:event_btnNhapLaiKHActionPerformed

    private void btnThemKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemKHActionPerformed
        // TODO add your handling code here:
//        txtMaKH.getText().isEmpty() |

        if (txtTenKH.getText().isEmpty() | txtDiaChiKH.getText().isEmpty() | txtDienThoai.getText().isEmpty() | txtEmail.getText().isEmpty() | txtSoTienNo.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Bạn chưa nhập đầy đủ thông tin, vui lòng nhập lại!");
        } else {
            kh.setMaKhachHang(txtMaKH.getText().trim());
            kh.setHoTenKhachHang(txtTenKH.getText().trim());

            kh.setDiaChi(txtDiaChiKH.getText().trim());
            kh.setEmaill(txtEmail.getText().trim());
            String txt = txtSoTienNo.getText();
            String sdt = txtDienThoai.getText().trim();
            try {
                int num = Integer.parseInt(txt);
                int sdtcheck = Integer.parseInt(sdt);
                kh.setSoDienThoai(sdt);
                kh.setSoTienNo(num);
                KhachHangData.Insert(kh);
                hienThiDanhSachKhachHang();
                // is an integer!
            } catch (NumberFormatException e) {
                // not an integer!
                JOptionPane.showMessageDialog(this, "số tiền nợ hoặc số điện thoại của khách hàng không hợp lệ vui lòng nhập lại");
            }

        }
    }//GEN-LAST:event_btnThemKHActionPerformed

    private void btnXoaKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaKHActionPerformed
        // TODO add your handling code here:
        KhachHangData.Delete(txtMaKH.getText().trim());
        hienThiDanhSachKhachHang();
    }//GEN-LAST:event_btnXoaKHActionPerformed

    private void txtQDNhapMinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQDNhapMinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQDNhapMinActionPerformed

    private void btnQDLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQDLuuActionPerformed
        // TODO add your handling code here:
        int j;
        if(txtApDungQD.getText() == "có")
        {
            j=1;
        } else {
            j=0;
        }
        try {
            int i = 1;
            ts.setMaThamSo(i);
            String QDnhapMin = txtQDNhapMin.getText().trim();
            int QDNhapMin2 = Integer.parseInt(QDnhapMin);
            String QDTonTrc = txtQDTonTrcKhiNhap.getText().trim();
            int QDTonTrc2 = Integer.parseInt(QDTonTrc);
            String QDTienNoMax = txtQDTienNoMax.getText().trim();
            int QDTienNoMax2 = Integer.parseInt(QDTienNoMax);
            String QDTonMin = txtQDTonMinSauKhiBan.getText().trim();
            int QDTonMin2 = Integer.parseInt(QDTonMin);

            ts.setSoLuongNhapItNhat(1);
            ts.setSoLuongTonToiDaTruocKhiNhap(2);
            ts.setSoLuongTonToiThieuSauKhiBan(2);
            ts.setSoTienNoToiDa(2);
            ts.setApDungQuyDinhSoTienThuKhongVuotQuaSoTienNo(j);
            ThamSoData.Update(ts);
            hienThiThamSo();
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "ban đã nhập sai định dạng vui lòng nhập lại");
        }
    }//GEN-LAST:event_btnQDLuuActionPerformed

    private void txtApDungQDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApDungQDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApDungQDActionPerformed

    private void btnQDMacDinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQDMacDinhActionPerformed
        // TODO add your handling code here
        txtQDNhapMin.setText("100");
        txtQDTonTrcKhiNhap.setText("20");
        txtQDTienNoMax.setText("500000");
        txtQDTonMinSauKhiBan.setText("10");
        txtApDungQD.setText("có");
    }//GEN-LAST:event_btnQDMacDinhActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JMain().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TableSach;
    private javax.swing.JButton btnBCCongNo;
    private javax.swing.JButton btnBCTon;
    private javax.swing.JButton btnCapNhapKH;
    private javax.swing.JButton btnCapNhatSach;
    private javax.swing.JButton btnNhapLaiKH;
    private javax.swing.JButton btnQDLuu;
    private javax.swing.JButton btnQDMacDinh;
    private javax.swing.JButton btnThemKH;
    private javax.swing.JButton btnThemSach;
    private javax.swing.JButton btnTimKH;
    private javax.swing.JButton btnTimSach;
    private javax.swing.JButton btnXoaKH;
    private javax.swing.JButton btnXóa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane tabSach;
    private javax.swing.JTable tbBaoCao;
    private javax.swing.JTable tbKhachHang;
    private javax.swing.JTextField txtApDungQD;
    private javax.swing.JTextField txtDiaChiKH;
    private javax.swing.JTextField txtDienThoai;
    private javax.swing.JTextField txtDonGia;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtMaKH;
    private javax.swing.JTextField txtMaSach;
    private javax.swing.JTextField txtQDNhapMin;
    private javax.swing.JTextField txtQDTienNoMax;
    private javax.swing.JTextField txtQDTonMinSauKhiBan;
    private javax.swing.JTextField txtQDTonTrcKhiNhap;
    private javax.swing.JTextField txtSLNhap;
    private javax.swing.JTextField txtSoTienNo;
    private javax.swing.JTextField txtTacGia;
    private javax.swing.JTextField txtTenKH;
    private javax.swing.JTextField txtTenSach;
    private javax.swing.JTextField txtTheLoai;
    private javax.swing.JTextField txtTimKH;
    private javax.swing.JTextField txtTimKiemSach;
    // End of variables declaration//GEN-END:variables
}
